substitutions:
  name: m5stack-atom-echo-31a9fc
  friendly_name: M5Stack Atom Echo 31a9fc
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.adopted.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: qkAXdYUWiCDPhdjMlYztRYqYUfGZEo3hQtENhumblRc=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
