substitutions:
  name: m5stack-atom-echo-31aaa4
  friendly_name: M5Stack Atom Echo 31aaa4
packages:
  m5stack.atom-echo-voice-assistant: github://esphome/firmware/voice-assistant/m5stack-atom-echo.adopted.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: TCAVmjgG0NC2Kf07uoM/Fc8MlArHCcrm5/Zsb/3PCjo=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
